steps:
  - name: "node:20"
    entrypoint: "npm"
    args: ["install", "@google-cloud/secret-manager"]
  - name: "node:20"
    entrypoint: "node"
    args: ["secret-manager.js"]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-f",
        "Dockerfile.production",
        "-t",
        "europe-west9-docker.pkg.dev/claudeallouche/api/api:lasted",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "europe-west9-docker.pkg.dev/claudeallouche/api/api:lasted"]
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "api",
        "--image",
        "europe-west9-docker.pkg.dev/claudeallouche/api/api:lasted",
        "--platform",
        "managed",
        "--region",
        "europe-west1",
        "--allow-unauthenticated",
      ]
