steps:
  - name: "node:20"
    entrypoint: "npm"
    args: ["install", "@google-cloud/secret-manager"]
  - name: "node:20"
    entrypoint: "node"
    args: ["secret-manager.js"]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-f",
        "Dockerfile.production",
        "-t",
        "us-central1-docker.pkg.dev/claudeallouche/cloud-run-source-deploy:lasted",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-central1-docker.pkg.dev/claudeallouche/cloud-run-source-deploy:lasted",
      ]
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "ahuza",
        "--image",
        "us-central1-docker.pkg.dev/claudeallouche/cloud-run-source-deploy:lasted",
        "--platform",
        "managed",
        "--region",
        "us-central1",
        "--allow-unauthenticated",
      ]
